### ISSUE TITLE
Crontab Groups System does not work correctly

### ISSUE THREAD

**Issue by alkemy-tech** [lsretailomni/lsmag-enterprise#1]
I have a Magento Commerce clean installation (v2.3.4) with only lsmag-enterprise extension installed.
After composer installation I configure LS Omni connection, cleaned cache and ran setup:di:compile,

After that I wait that replication job work for few hours, but when I checked data there was not any products or any categories in my platform.

To investigate the issue I checked cron_schedule table and I saw that "repl_" cronjobs were scheduled for just 2/3 times after extension installation.
Moreover some crontab were not executed and old records were not cleaned by Magento procedure.

Inside the code I noticed that there are 4 crontab groups (lscore, replication, flat_replication, sync_replication).
I thought it was a scheduling configuration problem, but in the Configuration - Advanced - System - Cron tab they were not visible.
So I tried to clean the cache and the cron groups came back visible again, but after 2/3 schedule run the problem recurs, and the crontab groups are no longer visible.
Same thing by trying to run the commands manually ("bin / magento cron: run" and "bin / magento cron: run --group replication").
If I launch a manual execution by cron listing page everything work well, so it seems that issue is related only to the crontab groups configuration.

As a final attempt I also tried to remove and install the extension, I tried lsmag-enterprise and lsmag-two separately, but there was not good news.

I hope that it's clear.
Thank you

**Comment by lsretailomni** [comment]
Hi @aTom-alkemy,

All LS Retail active partners can use LS Partner & Customer Portal to submit the technical support request. Also we might need your Magento instance access to debug the issue.

Partner Portal: https://portal.lsretail.com/
https://www.lsretail.com/contact-us
support@lsretail.com

Thanks
